[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-files = "0.6.6"
actix-web = "4.9.0"
hyper-sse = { version = "0.1.0", git = "https://github.com/kentaromiura/hyper-sse"}
lazy_static = "1.5.0"
notify = "8.0.0"
