// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Html from "./Html.res.mjs";
import * as State from "./State.res.mjs";
import * as Jotai from "jotai";
import * as Button from "./Button.res.mjs";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as JsxRuntime from "react/jsx-runtime";

function App(props) {
  var match = Jotai.useAtom(State.counter);
  var setCount = match[1];
  return JsxRuntime.jsxs(JsxRuntime.Fragment, {
              children: [
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("h1", {
                              children: "What is this about",
                              className: Html.css(["font-weight:500"], [])
                            }),
                        JsxRuntime.jsx("p", {
                              children: "This is a simple template for an ESBuild project using Rescript, Emotion CSS and Jotai."
                            }),
                        JsxRuntime.jsx(Button.make, {
                              children: Caml_option.some("Clicked " + match[0].toString() + " times"),
                              onClick: (function (param) {
                                  setCount(function (count) {
                                        return count + 1 | 0;
                                      });
                                })
                            })
                      ],
                      className: Html.css(["background-color: #f3f4f6;padding:20px"], [])
                    }),
                JsxRuntime.jsx("footer", {
                      children: JsxRuntime.jsx("img", {
                            className: Html.css(["\n    position: absolute;\n    top: 0;\n    left: 0px;\n    height: 52px;\n    z-index: 12;\n    width: auto;"], []),
                            src: "logo-index.png"
                          }),
                      className: Html.css(["\n    background-color: rgb(20, 22, 44);\n    color: rgb(36, 37, 56);\n    min-height: 50px;\n    position: relative;\n"], [])
                    })
              ]
            });
}

var make = App;

export {
  make ,
}
/* State Not a pure module */
