// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Html from "./Html.res.mjs";
import * as Util from "./Util.res.mjs";
import * as Caml_obj from "rescript/lib/es6/caml_obj.js";
import * as JsxRuntime from "react/jsx-runtime";

var pink = Html.css(["\n&:hover {\n    color: mistyrose;\n}"], []);

function make(props) {
  var newrecord = Caml_obj.obj_dup(props);
  return JsxRuntime.jsx("button", (newrecord.className = Util.cx([
                    pink,
                    Html.css(["background-color:#2563EB;"], [])
                  ]), newrecord));
}

export {
  pink ,
  make ,
}
/* pink Not a pure module */
