// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Html from "./Html.res.mjs";
import * as Caml_obj from "rescript/lib/es6/caml_obj.js";
import * as JsxRuntime from "react/jsx-runtime";

var pinkColor = "mistyrose";

var pink = Html.css([
      "\n&:hover {\n    color: ",
      ";\n}"
    ], [pinkColor]);

function make(props) {
  var newrecord = Caml_obj.obj_dup(props);
  return JsxRuntime.jsx("button", (newrecord.className = Html.cx([
                    pink,
                    Html.css(["background-color:#2563EB;"], [])
                  ]), newrecord));
}

export {
  pinkColor ,
  pink ,
  make ,
}
/* pink Not a pure module */
