// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Html from "./Html.res.mjs";
import * as Util from "./Util.res.mjs";
import * as State from "./State.res.mjs";
import * as Jotai from "jotai";
import * as JsxRuntime from "react/jsx-runtime";

var footerStyle = Html.css(["\n    background-color: rgb(20, 22, 44);\n    color: rgb(36, 37, 56);\n    min-height: 50px;\n    position: relative;\n"], []);

var logoStyle = Html.css(["\n    position: absolute;\n    top: 0;\n    left: 0px;\n    height: 52px;\n    z-index: 12;\n    width: auto;\n    transition: left 0.5s ease"], []);

function Footer(props) {
  var match = Jotai.useAtom(State.counter);
  return JsxRuntime.jsx("footer", {
              children: JsxRuntime.jsx("img", {
                    className: Util.cx([
                          logoStyle,
                          Html.css([
                                "left: ",
                                "px"
                              ], [Math.imul(match[0], 15).toString()])
                        ]),
                    src: "logo-index.png"
                  }),
              className: footerStyle
            });
}

var make = Footer;

export {
  footerStyle ,
  logoStyle ,
  make ,
}
/* footerStyle Not a pure module */
