// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Html from "./html";
import * as Caml_splice_call from "rescript/lib/es6/caml_splice_call.js";

function html(prim0, prim1) {
  return Caml_splice_call.spliceApply(Html.html, [
              prim0,
              prim1
            ]);
}

function getRendererFor(prim) {
  return Html.render(prim);
}

export {
  html ,
  getRendererFor ,
}
/* ./html Not a pure module */
