// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Caml_obj from "rescript/lib/es6/caml_obj.js";

function css(template, _holes) {
  return template.length.toString();
}

function cx(classes) {
  return classes.join(" ");
}

function styled(what, className) {
  return function (props) {
    if (what.TAG === "Component") {
      var cn = props.className;
      var newrecord = Caml_obj.obj_dup(props);
      newrecord.className = [
          className,
          cn !== undefined ? cn : ""
        ].join(" ");
      return React.createElement(what._0, newrecord);
    }
    var newrecord$1 = Caml_obj.obj_dup(props);
    var cn$1 = props.className;
    newrecord$1.className = [
        className,
        cn$1 !== undefined ? cn$1 : ""
      ].join(" ");
    return React.createElement(what._0, newrecord$1);
  };
}

function unsafeDrillProps(_p) {
  return _p;
}

export {
  css ,
  cx ,
  styled ,
  unsafeDrillProps ,
}
/* react Not a pure module */
