// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Html from "./Html.res.mjs";
import * as State from "./State.res.mjs";

function unref(refState) {
  return refState.contents;
}

var refRoot = {
  contents: undefined
};

function render(state, root) {
  var test = Html.html([
        "\n    <div>\n        TEST ",
        " ",
        " \n    </div>"
      ], [
        {
          NAME: "Int",
          VAL: 0
        },
        {
          NAME: "Str",
          VAL: "ciao"
        }
      ]);
  root([
        "\n    ",
        "\n    <div onclick=",
        ">\n        Hello, ",
        ", clicked: ",
        " times.\n    </div>"
      ], [
        {
          NAME: "Elements",
          VAL: [test]
        },
        {
          NAME: "Procedure",
          VAL: onClicked
        },
        {
          NAME: "Str",
          VAL: state.name
        },
        {
          NAME: "Int",
          VAL: state.iterations
        }
      ]);
}

function dispatch(action) {
  var root = refRoot.contents;
  var state = State.updateState(State.mutatedState.contents, action);
  if (root !== undefined) {
    render(state, root);
  }
  
}

function onClicked() {
  dispatch(State.Action.ofType("Update"));
}

function main() {
  var renderer = Html.getRendererFor(document.getElementById("root"));
  refRoot.contents = renderer;
  render(State.initialState, renderer);
}

window.onload=main
;

export {
  unref ,
  refRoot ,
  render ,
  dispatch ,
  onClicked ,
  main ,
}
/*  Not a pure module */
