// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Html from "./html";

function make(name, iterations) {
  return {
          iterations: iterations,
          name: name
        };
}

var State = {
  make: make
};

function ofType(actionType) {
  return {
          kind: actionType
        };
}

var Action = {
  ofType: ofType
};

function getRendererFor(prim) {
  return Html.render(prim);
}

var initialState = {
  iterations: 0,
  name: "world"
};

var mutatedState = {
  contents: initialState
};

function unref(refState) {
  return refState.contents;
}

function updateState(previous, action) {
  mutatedState.contents = {
    iterations: previous.iterations + 1 | 0,
    name: "updated 世界"
  };
  return mutatedState.contents;
}

var refRoot = {
  contents: undefined
};

function render(state, root) {
  root([
        "<div onclick=",
        ">\n    Hello, ",
        ", clicked: ",
        " times.\n    </div>"
      ], [
        {
          NAME: "Procedure",
          VAL: onClicked
        },
        {
          NAME: "Str",
          VAL: state.name
        },
        {
          NAME: "Int",
          VAL: state.iterations
        }
      ]);
}

function dispatch(action) {
  var root = refRoot.contents;
  var state = updateState(mutatedState.contents, action);
  if (root !== undefined) {
    render(state, root);
  }
  
}

function onClicked() {
  dispatch({
        kind: "Update"
      });
}

function main() {
  var renderer = Html.render(document.getElementById("root"));
  refRoot.contents = renderer;
  render(initialState, renderer);
}

window.onload=main
;

export {
  State ,
  Action ,
  getRendererFor ,
  initialState ,
  mutatedState ,
  unref ,
  updateState ,
  refRoot ,
  render ,
  dispatch ,
  onClicked ,
  main ,
}
/*  Not a pure module */
