// Generated by ReScript, PLEASE EDIT WITH CARE


function unref(refState) {
  return refState.contents;
}

function cx(classes) {
  return classes.join(" ");
}

export {
  unref ,
  cx ,
}
/* No side effect */
